'use client';

import { useEffect, useMemo, useRef, useState, type DragEvent } from 'react';
import CardModal from '@/components/CardModal';
import BoardCardChecklist from '@/components/BoardCardChecklist';
import NotificationCenter from '@/components/NotificationCenter';
import { supabase, supabaseConfigured } from '@/lib/supabase-browser';
import type { Board, BoardRole, Card, List } from '@/lib/types';
import './workspace.css';

type Profile = { id: string; full_name: string | null; avatar_url: string | null };
type ChecklistProgress = { total_items: number; completed_items: number };
type BoardSnapshot = { lists: List[]; cards: Card[]; profiles: Profile[] };
type Filter = 'all' | 'overdue' | 'today' | 'high';
type WorkspaceMember = { id: string; full_name: string | null; avatar_url: string | null };
type SelectedMember = { userId: string; role: Exclude<BoardRole, 'owner'> };

const priorityLabels = { low: 'Niedrig', normal: 'Normal', high: 'Hoch', urgent: 'Dringend' } as const;
const roleLabels: Record<BoardRole, string> = { owner: 'Eigentümer', admin: 'Administrator', member: 'Mitglied', viewer: 'Betrachter' };

function ChecklistProgressBadge({ progress }: { progress: ChecklistProgress | null }) {
  if (!progress || progress.total_items === 0) return null;
  const percent = Math.round((progress.completed_items / progress.total_items) * 100);
  return <div className="checklist-card-progress" aria-label={`Checkliste: ${progress.completed_items} von ${progress.total_items} erledigt`}><div className="checklist-card-head"><span>Checkliste</span><strong>{progress.completed_items}/{progress.total_items}</strong></div><div className="checklist-card-bar"><span style={{ width: `${percent}%` }} /></div></div>;
}

function MenuIcon({ children }: { children: React.ReactNode }) { return <span className="menu-icon" aria-hidden="true">{children}</span>; }

export default function Home() {
  const [userId, setUserId] = useState<string | null>(null); const [userEmail, setUserEmail] = useState<string | null>(null); const [boards, setBoards] = useState<Board[]>([]); const [lists, setLists] = useState<List[]>([]); const [cards, setCards] = useState<Card[]>([]); const [profiles, setProfiles] = useState<Profile[]>([]); const [checklistProgress, setChecklistProgress] = useState<Record<string, ChecklistProgress>>({}); const [selectedBoard, setSelectedBoard] = useState<string | null>(null); const [selectedCard, setSelectedCard] = useState<Card | null>(null); const [loading, setLoading] = useState(supabaseConfigured); const [notice, setNotice] = useState(''); const [search, setSearch] = useState(''); const [filter, setFilter] = useState<Filter>('all'); const [draggedCardId, setDraggedCardId] = useState<string | null>(null); const [dragOverCardId, setDragOverCardId] = useState<string | null>(null); const [movingCard, setMovingCard] = useState(false); const [boardRefreshVersion, setBoardRefreshVersion] = useState(0); const [myRole, setMyRole] = useState<BoardRole | null>(null); const [createOpen, setCreateOpen] = useState(false); const [createName, setCreateName] = useState(''); const [createDescription, setCreateDescription] = useState(''); const [createDate, setCreateDate] = useState(''); const [workspaceMembers, setWorkspaceMembers] = useState<WorkspaceMember[]>([]); const [selectedMembers, setSelectedMembers] = useState<SelectedMember[]>([]); const [createBusy, setCreateBusy] = useState(false); const [boardDate, setBoardDate] = useState(''); const [boardDateSaving, setBoardDateSaving] = useState(false); const listsRef = useRef<List[]>([]);
  const activeBoard = selectedBoard ? boards.find((board) => board.id === selectedBoard) ?? null : null;
  const selectedBoardStorageKey = userId ? `essentia.activeBoard.${userId}` : null;
  const activeLists = useMemo(() => lists.filter((list) => list.board_id === activeBoard?.id).sort((a, b) => a.position - b.position), [lists, activeBoard]);
  const activeCards = useMemo(() => cards.filter((card) => activeLists.some((list) => list.id === card.list_id)).sort((a, b) => a.position - b.position), [cards, activeLists]);
  const visibleCards = useMemo(() => { const query = search.trim().toLowerCase(); const now = new Date(); const start = new Date(now.getFullYear(), now.getMonth(), now.getDate()); const end = new Date(start); end.setDate(end.getDate() + 1); return activeCards.filter((card) => { const assignee = profiles.find((p) => p.id === card.assignee_id)?.full_name ?? ''; if (query && !`${card.title} ${card.description ?? ''} ${priorityLabels[card.priority ?? 'normal']} ${assignee}`.toLowerCase().includes(query)) return false; if (filter === 'all') return true; if (filter === 'high') return card.priority === 'high' || card.priority === 'urgent'; if (!card.due_at) return false; const due = new Date(card.due_at); return filter === 'overdue' ? due < now : due >= start && due < end; }); }, [activeCards, search, profiles, filter]);
  const canManage = myRole === 'owner' || myRole === 'admin';
  useEffect(() => { setBoardDate(activeBoard?.scheduled_date ?? ''); }, [activeBoard?.id, activeBoard?.scheduled_date]);
  async function saveBoardDate(value: string) { const client = supabase; if (!client || !activeBoard || !canManage) return; setBoardDate(value); setBoardDateSaving(true); const { data, error } = await client.from('boards').update({ scheduled_date: value || null }).eq('id', activeBoard.id).select().single(); if (error || !data) setNotice(error?.message ?? 'Board-Datum konnte nicht gespeichert werden.'); else setBoards(current => current.map(board => board.id === activeBoard.id ? data as Board : board)); setBoardDateSaving(false); } const canEditCards = canManage || myRole === 'member';
  useEffect(() => { if (typeof window === 'undefined' || !selectedBoardStorageKey || !selectedBoard) return; window.localStorage.setItem(selectedBoardStorageKey, selectedBoard); }, [selectedBoard, selectedBoardStorageKey]);
  useEffect(() => { listsRef.current = lists; }, [lists]);
  async function loadBoards() { const client = supabase; if (!client) return; setLoading(true); const { data: session } = await client.auth.getSession(); const user = session.session?.user; setUserId(user?.id ?? null); setUserEmail(user?.email ?? null); if (!user) { setBoards([]); setLoading(false); return; } await client.functions.invoke('board-invites', { body: { action: 'sync' } }); const { data, error } = await client.from('boards').select('*').order('updated_at', { ascending: false }); if (error) setNotice(error.message); else { const next = (data ?? []) as Board[]; setBoards(next); setSelectedBoard(current => { if (current && next.some(b => b.id === current)) return current; if (typeof window !== 'undefined' && selectedBoardStorageKey) { const stored = window.localStorage.getItem(selectedBoardStorageKey); if (stored && next.some(b => b.id === stored)) return stored; } return next[0]?.id ?? null; }); } setLoading(false); }
  async function loadBoardContent(boardId: string) { const client = supabase; if (!client) return; const { data, error } = await client.rpc('get_board_snapshot', { p_board_id: boardId }); if (error) { setNotice(error.message); return; } const snapshot = data as BoardSnapshot | null; if (snapshot) { setLists(snapshot.lists ?? []); setCards(snapshot.cards ?? []); setProfiles(snapshot.profiles ?? []); } if (userId) { const roleResult = await client.from('board_members').select('role').eq('board_id', boardId).eq('user_id', userId).maybeSingle(); setMyRole((roleResult.data?.role as BoardRole | undefined) ?? null); } }
  async function loadChecklistProgress(boardId: string) { const client = supabase; if (!client) return; const listIds = lists.filter(l => l.board_id === boardId).map(l => l.id); const cardIds = cards.filter(c => listIds.includes(c.list_id)).map(c => c.id); if (!cardIds.length) { setChecklistProgress({}); return; } const { data, error } = await client.from('card_checklist_progress').select('card_id,total_items,completed_items').in('card_id', cardIds); if (error) { setNotice(error.message); return; } const next: Record<string, ChecklistProgress> = {}; for (const row of data ?? []) next[row.card_id] = { total_items: row.total_items, completed_items: row.completed_items }; setChecklistProgress(next); }
  async function loadWorkspaceMembers() { const client = supabase; if (!client || !userId) return; const { data: boardRows } = await client.from('boards').select('id').order('updated_at', { ascending: false }); const boardIds = (boardRows ?? []).map((row: { id: string }) => row.id); if (!boardIds.length) { setWorkspaceMembers([]); return; } const { data: members } = await client.from('board_members').select('user_id').in('board_id', boardIds); const ids = [...new Set((members ?? []).map((row: { user_id: string }) => row.user_id).filter(id => id !== userId))]; if (!ids.length) { setWorkspaceMembers([]); return; } const { data: people, error } = await client.from('profiles').select('id,full_name,avatar_url').in('id', ids).order('full_name'); if (error) { setNotice(error.message); return; } setWorkspaceMembers((people ?? []) as WorkspaceMember[]); }
  useEffect(() => { void loadBoards(); const client = supabase; if (!client) return; const { data } = client.auth.onAuthStateChange((_event, session) => { setUserId(session?.user?.id ?? null); setUserEmail(session?.user?.email ?? null); if (!session) { setBoards([]); setLists([]); setCards([]); setProfiles([]); setSelectedBoard(null); setSelectedCard(null); } }); return () => data.subscription.unsubscribe(); }, []);
  useEffect(() => { if (selectedBoard) void loadBoardContent(selectedBoard); else { setLists([]); setCards([]); setProfiles([]); setMyRole(null); } }, [selectedBoard, userId]);
  useEffect(() => { if (activeBoard) void loadChecklistProgress(activeBoard.id); }, [activeBoard?.id, cards, lists, boardRefreshVersion]);
  useEffect(() => { if (!supabase || !activeBoard) return; const client = supabase; const boardId = activeBoard.id; const channel = client.channel(`workspace-board-${boardId}`).on('postgres_changes', { event: '*', schema: 'public', table: 'lists', filter: `board_id=eq.${boardId}` }, () => void loadBoardContent(boardId)).on('postgres_changes', { event: '*', schema: 'public', table: 'cards' }, payload => { const next = payload.new as Card; const old = payload.old as Card; const listIds = new Set(listsRef.current.filter(l => l.board_id === boardId).map(l => l.id)); const relevant = (c: Card) => !!c?.list_id && listIds.has(c.list_id); if (payload.eventType === 'INSERT' && relevant(next)) setCards(current => current.some(c => c.id === next.id) ? current : [...current, next]); else if (payload.eventType === 'UPDATE') setCards(current => relevant(next) ? current.some(c => c.id === next.id) ? current.map(c => c.id === next.id ? next : c) : [...current, next] : current.filter(c => c.id !== old.id)); else if (payload.eventType === 'DELETE') setCards(current => current.filter(c => c.id !== old.id)); }).on('postgres_changes', { event: '*', schema: 'public', table: 'card_checklist_items' }, () => setBoardRefreshVersion(v => v + 1)).on('postgres_changes', { event: '*', schema: 'public', table: 'board_members', filter: `board_id=eq.${boardId}` }, () => void loadBoardContent(boardId)).subscribe(); return () => { void client.removeChannel(channel); }; }, [activeBoard?.id]);
  async function openCreateBoard() { setCreateName(''); setCreateDescription(''); setCreateDate(''); setSelectedMembers([]); setCreateOpen(true); await loadWorkspaceMembers(); }
  function toggleMember(id: string) { setSelectedMembers(current => current.some(m => m.userId === id) ? current.filter(m => m.userId !== id) : [...current, { userId: id, role: 'member' }]); }
  function changeSelectedMemberRole(id: string, role: SelectedMember['role']) { setSelectedMembers(current => current.map(m => m.userId === id ? { ...m, role } : m)); }
  async function createBoard() { const client = supabase; if (!client || !userId || !createName.trim() || createBusy) return; setCreateBusy(true); setNotice(''); const { data: created, error } = await client.rpc('create_board_with_defaults', { p_name: createName.trim(), p_description: createDescription.trim() || null, p_scheduled_date: createDate || null }); const board = created as Board | null; if (error || !board) { setNotice(error?.message ?? 'Board konnte nicht erstellt werden.'); setCreateBusy(false); return; } if (selectedMembers.length) { const { error: memberError } = await client.from('board_members').insert(selectedMembers.map(member => ({ board_id: board.id, user_id: member.userId, role: member.role }))); if (memberError) setNotice(`Board wurde erstellt, einige Mitglieder konnten nicht hinzugefügt werden: ${memberError.message}`); } setCreateOpen(false); setCreateBusy(false); await loadBoards(); setSelectedBoard(board.id); }
  async function addList() { const client = supabase; if (!client || !activeBoard || !canManage) return; const name = window.prompt('Name der neuen Liste', 'Neue Liste'); if (!name?.trim()) return; const { data, error } = await client.from('lists').insert({ board_id: activeBoard.id, name: name.trim(), position: activeLists.length }).select().single(); if (error) setNotice(error.message); else if (data) setLists(current => [...current, data as List]); }
  async function renameList(list: List) { const client = supabase; if (!client || !canManage) return; const name = window.prompt('Liste umbenennen', list.name); if (!name?.trim() || name.trim() === list.name) return; const { error } = await client.from('lists').update({ name: name.trim() }).eq('id', list.id); if (error) setNotice(error.message); else setLists(current => current.map(item => item.id === list.id ? { ...item, name: name.trim() } : item)); }
  async function deleteList(list: List) { const client = supabase; if (!client || !canManage) return; if (!window.confirm(`Liste „${list.name}“ wirklich löschen? Die enthaltenen Aufgaben werden ebenfalls gelöscht.`)) return; const { error } = await client.from('lists').delete().eq('id', list.id); if (error) setNotice(error.message); else setLists(current => current.filter(item => item.id !== list.id)); }
  async function addCard(listId: string) { const client = supabase; if (!client || !canEditCards) return; const title = window.prompt('Neue Aufgabe', 'Neue Aufgabe'); if (!title?.trim()) return; const listCards = cards.filter(c => c.list_id === listId); const position = listCards.length ? Math.max(...listCards.map(c => c.position)) + 1 : 0; const { data, error } = await client.from('cards').insert({ list_id: listId, title: title.trim(), position, priority: 'normal', created_by: userId }).select().single(); if (error) setNotice(error.message); else if (data) setCards(current => current.some(c => c.id === data.id) ? current : [...current, data as Card]); }
  async function moveCard(cardId: string, targetListId: string, beforeCardId: string | null = null) { const client = supabase; if (!client || !canEditCards || movingCard) return; const card = cards.find(c => c.id === cardId); if (!card || beforeCardId === cardId) return; setMovingCard(true); setDraggedCardId(cardId); const { error } = await client.rpc('move_card', { p_card_id: cardId, p_target_list_id: targetListId, p_before_card_id: beforeCardId }); if (error) setNotice(error.message); if (activeBoard) await loadBoardContent(activeBoard.id); setMovingCard(false); setDraggedCardId(null); setDragOverCardId(null); }
  function onCardDragStart(event: DragEvent<HTMLButtonElement>, cardId: string) { if (!canEditCards) { event.preventDefault(); return; } setDraggedCardId(cardId); event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', cardId); }
  function onCardDragOver(event: DragEvent<HTMLButtonElement>, cardId: string) { event.preventDefault(); if (!draggedCardId || draggedCardId === cardId) return; setDragOverCardId(cardId); event.dataTransfer.dropEffect = 'move'; }
  function onCardDrop(event: DragEvent<HTMLButtonElement>, targetCard: Card) { event.preventDefault(); const cardId = draggedCardId || event.dataTransfer.getData('text/plain'); if (cardId) void moveCard(cardId, targetCard.list_id, targetCard.id); }
  function onColumnDrop(event: DragEvent<HTMLDivElement>, listId: string) { event.preventDefault(); const cardId = draggedCardId || event.dataTransfer.getData('text/plain'); if (cardId) void moveCard(cardId, listId, null); }
  async function openNotificationCard(cardId: string) { const card = cards.find(c => c.id === cardId); if (card) { setSelectedCard(card); return; } if (activeBoard && supabase) { await loadBoardContent(activeBoard.id); const { data } = await supabase.from('cards').select('*').eq('id', cardId).maybeSingle(); if (data) setSelectedCard(data as Card); } }
  async function signOut() { if (supabase) await supabase.auth.signOut(); setUserId(null); setUserEmail(null); setBoards([]); setLists([]); setCards([]); setProfiles([]); setSelectedBoard(null); setSelectedCard(null); }

  return <main className="shell boards-workspace-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">O</span><span>Essentia</span></div><nav><a className="active" href="#dashboard"><MenuIcon>⌂</MenuIcon>Übersicht</a><a href="/boards"><MenuIcon>▦</MenuIcon>Meine Boards</a><a href="/tasks"><MenuIcon>☑</MenuIcon>Aufgaben</a><a href="/team"><MenuIcon>♙</MenuIcon>Team</a><a href="/calendar"><MenuIcon>□</MenuIcon>Kalender</a><a href="/documents"><MenuIcon>▤</MenuIcon>Dokumente</a><a href="/settings"><MenuIcon>⚙</MenuIcon>Einstellungen</a></nav><div className="sidebar-footer"><strong>Essentia Team</strong><span>{userEmail ?? 'Professionelle Zusammenarbeit'}</span></div></aside>
    <section className="content workspace-content" id="dashboard">
      <header className="topbar"><div className="global-search-wrap"><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Aufgaben, Boards oder Inhalte suchen …" aria-label="Global suchen"/><kbd>⌘ K</kbd></div><div className="top-actions">{userEmail && <NotificationCenter onOpenCard={openNotificationCard} />}{userEmail ? <button className="profile-chip" title={userEmail}><span>{(userEmail.slice(0,1) || 'U').toUpperCase()}</span><strong>{userEmail.split('@')[0]}</strong><small>Administrator</small></button> : <a className="ghost button-link" href="/auth">Anmelden</a>}{userEmail && <button className="ghost compact-action" onClick={signOut}>Abmelden</button>}</div></header>
      {!supabaseConfigured && <div className="setup-banner"><strong>Supabase-Verbindung fehlt.</strong><span>Für echte Benutzer, Boards und Echtzeit-Daten müssen die NEXT_PUBLIC_SUPABASE_* Variablen gesetzt werden.</span></div>}
      {notice && <div className="notice">{notice}<button onClick={() => setNotice('')}>×</button></div>}
      <section className="board-strip-section"><div className="board-strip-head"><div><p className="eyebrow">Meine Boards</p><span>Alle aktiven Arbeitsflächen, an denen du beteiligt bist</span></div><strong>{boards.length}</strong></div><div className="board-strip">{boards.map(board => <button key={board.id} className={`board-tab ${activeBoard?.id === board.id ? 'active' : ''}`} onClick={() => setSelectedBoard(board.id)}><span className="board-tab-mark">{board.name.slice(0, 1).toUpperCase()}</span><span className="board-tab-copy"><strong>{board.name}</strong><small>{board.description || 'Kanban-Arbeitsfläche'}</small></span></button>)}{userEmail && <button className="board-tab board-tab-add" onClick={() => void openCreateBoard()}>＋ <span>Neues Board</span></button>}</div></section>
      {loading ? <div className="empty-state"><h3>Boards werden geladen …</h3></div> : !activeBoard ? <div className="empty-state"><h3>Noch kein Board vorhanden</h3><p>Erstelle dein erstes Board oder lass dich zu einem bestehenden Board hinzufügen.</p><button className="primary" onClick={() => void openCreateBoard()}>+ Erstes Board erstellen</button></div> : <>
        <section className="workspace-header"><div><p className="eyebrow">Arbeitsfläche</p><h2>{activeBoard.name}<button className="inline-settings" aria-label="Board-Einstellungen" title="Board-Einstellungen">⚙</button></h2><p className="muted">{activeBoard.description || 'Aufgaben organisieren. Projekte voranbringen.'}</p></div><div className="top-actions"><label className="board-date-field"><span>Board-Datum</span><input type="date" value={boardDate} onChange={e => void saveBoardDate(e.target.value)} disabled={!canManage || boardDateSaving} aria-label="Board-Datum" /></label><button className="workspace-icon-button" title="Suchen">⌕</button><select className="filter-select" value={filter} onChange={e => setFilter(e.target.value as Filter)} aria-label="Aufgaben filtern"><option value="all">Alle Aufgaben</option><option value="overdue">Überfällig</option><option value="today">Heute fällig</option><option value="high">Hohe Priorität</option></select>{canManage && <button className="ghost" onClick={() => void addList()}>＋ Neue Liste</button>}</div></section>
        <section className="kanban-board" aria-label={`Board ${activeBoard.name}`}>
          {activeLists.map(list => { const listCards = visibleCards.filter(card => card.list_id === list.id); return <div className={`kanban-column ${draggedCardId ? 'drag-active' : ''}`} key={list.id} onDragOver={e => e.preventDefault()} onDrop={e => onColumnDrop(e, list.id)}><header><div><h3>{list.name}<span className="count-pill">{listCards.length}</span></h3></div>{canManage && <div className="top-actions"><button className="column-menu" title="Liste umbenennen" onClick={() => void renameList(list)}>•••</button><button className="column-menu" title="Liste löschen" onClick={() => void deleteList(list)}>×</button></div>}</header><div className="kanban-cards">{listCards.map(card => { const isTodoCard = card.title.trim().toLowerCase() === 'to-do-liste'; if (isTodoCard) { return <article key={card.id} className="kanban-card kanban-card-todo" aria-label="To-do-Liste"><strong>{card.title}</strong><BoardCardChecklist cardId={card.id} canEdit={canEditCards} /></article>; } return <button key={card.id} className={`kanban-card ${dragOverCardId === card.id ? 'drag-over' : ''}`} draggable={canEditCards} onDragStart={e => onCardDragStart(e, card.id)} onDragOver={e => onCardDragOver(e, card.id)} onDragLeave={() => setDragOverCardId(current => current === card.id ? null : current)} onDrop={e => onCardDrop(e, card)} onDragEnd={() => { setDraggedCardId(null); setDragOverCardId(null); }} onClick={() => setSelectedCard(card)}><strong>{card.title}</strong>{card.description && <span>{card.description}</span>}<small>{priorityLabels[card.priority ?? 'normal']}{card.assignee_id ? ` · ${profiles.find(p => p.id === card.assignee_id)?.full_name || 'Teammitglied'}` : ''}{card.due_at ? ` · ${new Date(card.due_at).toLocaleDateString('de-DE')}` : ''}</small><ChecklistProgressBadge progress={checklistProgress[card.id] ?? null} /></button>; })}{canEditCards && <button className="add-card-link" onClick={() => void addCard(list.id)}>＋ Aufgabe hinzufügen</button>}</div></div>; })}
          {canManage && <button className="add-column" onClick={() => void addList()}>＋ Weitere Liste</button>}
        </section>
      </>}
      {selectedCard && <CardModal card={selectedCard} onClose={() => setSelectedCard(null)} onSaved={card => { setCards(current => current.map(item => item.id === card.id ? card : item)); setSelectedCard(card); }} onDeleted={cardId => { setCards(current => current.filter(item => item.id !== cardId)); setSelectedCard(null); }} />}
    </section>
    {createOpen && <div className="board-create-overlay" role="dialog" aria-modal="true" aria-labelledby="create-board-title"><div className="board-create-dialog"><header><div><p className="eyebrow">Neue Arbeitsfläche</p><h2 id="create-board-title">Board erstellen</h2><p>Wähle direkt die Teammitglieder aus, die bereits in deinem Arbeitsbereich vorhanden sind.</p></div><button className="modal-close" onClick={() => setCreateOpen(false)} aria-label="Schließen">×</button></header><div className="board-create-fields"><label>Boardname<input value={createName} onChange={e => setCreateName(e.target.value)} placeholder="z. B. Bauvorhaben Saarland" autoFocus /></label><label>Beschreibung<textarea value={createDescription} onChange={e => setCreateDescription(e.target.value)} placeholder="Worum geht es in diesem Board?" rows={3} /></label><label>Board-Datum / Kalendereintrag<input type="date" value={createDate} onChange={e => setCreateDate(e.target.value)} /><small className="field-hint">Optional. Das Datum wird automatisch im Kalender beim Board angezeigt.</small></label></div><div className="member-picker"><div className="member-picker-head"><div><strong>Teammitglieder</strong><span>Optional – Personen können später ebenfalls verwaltet werden.</span></div><strong>{selectedMembers.length} ausgewählt</strong></div>{workspaceMembers.length ? <div className="member-picker-list">{workspaceMembers.map(member => { const selected = selectedMembers.find(item => item.userId === member.id); return <div key={member.id} className={`member-picker-row ${selected ? 'selected' : ''}`}><label><input type="checkbox" checked={!!selected} onChange={() => toggleMember(member.id)} /><span><strong>{member.full_name || 'Teammitglied'}</strong><small>Bereits im Arbeitsbereich</small></span></label>{selected && <select value={selected.role} onChange={e => changeSelectedMemberRole(member.id, e.target.value as SelectedMember['role'])}><option value="admin">Administrator</option><option value="member">Mitglied</option><option value="viewer">Betrachter</option></select>}</div>})}</div> : <div className="member-picker-empty">Es wurden noch keine anderen Teammitglieder gefunden. Du kannst das Board trotzdem erstellen und später Personen einladen.</div>}</div><footer><button className="ghost" onClick={() => setCreateOpen(false)} disabled={createBusy}>Abbrechen</button><button className="primary" onClick={() => void createBoard()} disabled={createBusy || !createName.trim()}>{createBusy ? 'Wird erstellt …' : 'Board erstellen'}</button></footer></div></div>}
  </main>;
}
