import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
async function sha256(value:string){const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return Array.from(bytes).map(b=>b.toString(16).padStart(2,"0")).join("")}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const authHeader=req.headers.get("Authorization");if(!authHeader)return json({error:"Nicht angemeldet."},401);const url=Deno.env.get("SUPABASE_URL")!;const serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const admin=createClient(url,serviceKey);const accessToken=authHeader.replace(/^Bearer\s+/i,"");const {data:authData,error:authError}=await admin.auth.getUser(accessToken);const user=authData.user;if(authError||!user)return json({error:"Ungültige Sitzung."},401);const body=await req.json();
if(body.action==="create"){const{board_id,email,role="member"}=body;if(!board_id||!email)return json({error:"Board und E-Mail sind erforderlich."},400);const normalizedEmail=String(email).trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(normalizedEmail))return json({error:"Ungültige E-Mail-Adresse."},400);if(!["admin","member","viewer"].includes(role))return json({error:"Ungültige Rolle."},400);const{data:board}=await admin.from("boards").select("id,owner_id").eq("id",board_id).maybeSingle();if(!board)return json({error:"Board nicht gefunden."},404);if(board.owner_id!==user.id){const{data:membership}=await admin.from("board_members").select("role").eq("board_id",board_id).eq("user_id",user.id).maybeSingle();if(!membership||!["owner","admin"].includes(membership.role))return json({error:"Keine Berechtigung."},403)}const{data:existingUser}=await admin.auth.admin.listUsers({page:1,perPage:1000});const match=existingUser.users.find(candidate=>candidate.email?.toLowerCase()===normalizedEmail);if(match){const{data:existingMember}=await admin.from("board_members").select("user_id").eq("board_id",board_id).eq("user_id",match.id).maybeSingle();if(existingMember)return json({error:"Diese Person ist bereits Mitglied des Boards."},409)}const rawToken=randomToken();const tokenHash=await sha256(rawToken);await admin.from("board_invitations").delete().eq("board_id",board_id).eq("email",normalizedEmail).is("accepted_at",null);const{data:invitation,error}=await admin.from("board_invitations").insert({board_id,email:normalizedEmail,role,created_by:user.id,token_hash:tokenHash}).select("expires_at").single();if(error)return json({error:error.message},500);return json({token:rawToken,expires_at:invitation.expires_at})}
if(body.action==="accept"){const rawToken=String(body.token??"").trim();if(!rawToken)return json({error:"Einladungslink fehlt."},400);const tokenHash=await sha256(rawToken);const{data:invitation}=await admin.from("board_invitations").select("id,board_id,email,role,expires_at,accepted_at").eq("token_hash",tokenHash).maybeSingle();if(!invitation)return json({error:"Einladung nicht gefunden."},404);if(invitation.accepted_at)return json({error:"Diese Einladung wurde bereits verwendet."},409);if(new Date(invitation.expires_at).getTime()<Date.now())return json({error:"Diese Einladung ist abgelaufen."},410);if(user.email?.toLowerCase()!==invitation.email.toLowerCase())return json({error:`Die Einladung ist für ${invitation.email} bestimmt. Bitte mit dieser E-Mail-Adresse anmelden.`},403);const{error:memberError}=await admin.from("board_members").upsert({board_id:invitation.board_id,user_id:user.id,role:invitation.role},{onConflict:"board_id,user_id"});if(memberError)return json({error:memberError.message},500);const{error:acceptError}=await admin.from("board_invitations").update({accepted_at:new Date().toISOString()}).eq("id",invitation.id).is("accepted_at",null);if(acceptError)return json({error:acceptError.message},500);return json({board_id:invitation.board_id})}return json({error:"Unbekannte Aktion."},400)}catch(error){return json({error:error instanceof Error?error.message:"Unbekannter Fehler."},500)}});
