'use client';
import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase-browser';
import type { Board } from '@/lib/types';
export default function SettingsPage(){
 const [userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState(''),[name,setName]=useState(''),[boards,setBoards]=useState<Board[]>([]),[boardId,setBoardId]=useState(''),[boardName,setBoardName]=useState(''),[description,setDescription]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const board=boards.find(b=>b.id===boardId);const canEdit=!!board&&board.owner_id===userId;
 async function load(){if(!supabase)return;const {data:s}=await supabase.auth.getSession();const u=s.session?.user;if(!u)return;setUserId(u.id);setEmail(u.email??'');const {data:p}=await supabase.from('profiles').select('full_name').eq('id',u.id).maybeSingle();setName(p?.full_name??'');const {data:b,error}=await supabase.from('boards').select('*').order('updated_at',{ascending:false});if(error)return setNotice(error.message);setBoards(b??[]);setBoardId(b?.[0]?.id??'')}
 useEffect(()=>{load()},[]);useEffect(()=>{if(board){setBoardName(board.name);setDescription(board.description??'')}},[board]);
 async function saveProfile(){if(!supabase||!userId)return;setBusy(true);const {error}=await supabase.from('profiles').update({full_name:name.trim()||null,updated_at:new Date().toISOString()}).eq('id',userId);setNotice(error?.message??'Profil gespeichert.');setBusy(false)}
 async function saveBoard(){if(!supabase||!board||!canEdit)return;setBusy(true);const {data,error}=await supabase.from('boards').update({name:boardName.trim()||board.name,description:description.trim()||null,updated_at:new Date().toISOString()}).eq('id',board.id).select().single();if(error)setNotice(error.message);else{setBoards(bs=>bs.map(b=>b.id===board.id?data as Board:b));setNotice('Board gespeichert.')}setBusy(false)}
 async function signOut(){if(supabase)await supabase.auth.signOut();window.location.href='/'}
 if(!userId)return <main className="auth-shell"><section className="auth-card"><div className="brand auth-brand"><span className="brand-mark">O</span><span>Orgaplattform</span></div><h1>Einstellungen</h1><p className="auth-copy">Bitte melde dich an.</p><a className="primary button-link auth-submit" href="/auth">Anmelden</a></section></main>;
 return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">O</span><span>Orgaplattform</span></div><nav><a href="/">Übersicht</a><a href="/#boards">Meine Boards</a><a href="/team">Team</a><a className="active" href="/settings">Einstellungen</a></nav><div className="sidebar-footer">{email}</div></aside><section className="content"><header className="topbar"><div><div className="eyebrow">Konto</div><h1>Einstellungen</h1></div><div className="top-actions"><button className="ghost" onClick={signOut}>Abmelden</button><a className="primary button-link" href="/">Dashboard</a></div></header>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<section className="settings-grid"><div className="settings-card"><p className="eyebrow">Mein Profil</p><h2>Persönliche Daten</h2><label className="settings-field"><span>E-Mail</span><input value={email} readOnly/></label><label className="settings-field"><span>Name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Vor- und Nachname"/></label><button className="primary" onClick={saveProfile} disabled={busy}>Profil speichern</button></div><div className="settings-card"><p className="eyebrow">Board</p><h2>Board-Einstellungen</h2><label className="settings-field"><span>Board</span><select value={boardId} onChange={e=>setBoardId(e.target.value)}>{boards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="settings-field"><span>Name</span><input value={boardName} onChange={e=>setBoardName(e.target.value)} disabled={!canEdit}/></label><label className="settings-field"><span>Beschreibung</span><textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)} disabled={!canEdit}/></label><button className="primary" onClick={saveBoard} disabled={busy||!canEdit}>Board speichern</button>{!canEdit&&<p className="settings-hint">Nur der Eigentümer kann Board-Einstellungen ändern.</p>}</div></section></section></main>;
}
