'use client';
import { useEffect, useState } from 'react';
import WorkspaceModulePage from '@/components/WorkspaceModulePage';
import { supabase } from '@/lib/supabase-browser';
import type { Board } from '@/lib/types';
export default function SettingsPage(){
 const [userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState(''),[name,setName]=useState(''),[boards,setBoards]=useState<Board[]>([]),[boardId,setBoardId]=useState(''),[boardName,setBoardName]=useState(''),[description,setDescription]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const board=boards.find(b=>b.id===boardId),canEdit=!!board&&board.owner_id===userId;
 async function load(){if(!supabase)return;const {data:s}=await supabase.auth.getSession(),u=s.session?.user;if(!u)return;setUserId(u.id);setEmail(u.email??'');const {data:p}=await supabase.from('profiles').select('full_name').eq('id',u.id).maybeSingle();setName(p?.full_name??'');const {data:b,error}=await supabase.from('boards').select('*').order('updated_at',{ascending:false});if(error){setNotice(error.message);return}setBoards((b??[]) as Board[]);setBoardId(b?.[0]?.id??'')}
 useEffect(()=>{void load()},[]);useEffect(()=>{if(board){setBoardName(board.name);setDescription(board.description??'')}},[board]);
 async function saveProfile(){if(!supabase||!userId)return;setBusy(true);const {error}=await supabase.from('profiles').update({full_name:name.trim()||null,updated_at:new Date().toISOString()}).eq('id',userId);setNotice(error?.message??'Profil gespeichert.');setBusy(false)}
 async function saveBoard(){if(!supabase||!board||!canEdit)return;setBusy(true);const {data,error}=await supabase.from('boards').update({name:boardName.trim()||board.name,description:description.trim()||null,updated_at:new Date().toISOString()}).eq('id',board.id).select().single();if(error)setNotice(error.message);else{setBoards(bs=>bs.map(b=>b.id===board.id?data as Board:b));setNotice('Board gespeichert.')}setBusy(false)}
 return <WorkspaceModulePage title="Einstellungen" eyebrow="Konto" active="Einstellungen" description="Profil, Boards und persönliche Einstellungen zentral verwalten."><section className="settings-grid"><div className="settings-card"><p className="eyebrow">Mein Profil</p><h2>Persönliche Daten</h2><label className="settings-field"><span>E-Mail</span><input value={email} readOnly/></label><label className="settings-field"><span>Name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Vor- und Nachname"/></label><button className="primary" onClick={saveProfile} disabled={busy}>Profil speichern</button></div><div className="settings-card"><p className="eyebrow">Board</p><h2>Board-Einstellungen</h2><label className="settings-field"><span>Board</span><select value={boardId} onChange={e=>setBoardId(e.target.value)}>{boards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="settings-field"><span>Name</span><input value={boardName} onChange={e=>setBoardName(e.target.value)} disabled={!canEdit}/></label><label className="settings-field"><span>Beschreibung</span><textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)} disabled={!canEdit}/></label><button className="primary" onClick={saveBoard} disabled={busy||!canEdit}>Board speichern</button>{!canEdit&&<p className="settings-hint">Nur der Eigentümer kann Board-Einstellungen ändern.</p>}</div>{notice&&<div className="notice settings-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</section></WorkspaceModulePage>;
}
